--- 
stages:
  - check
  - build
  - test
  - deploy
  - release
  - cleanup

variables:
  DOCKER_DRIVER: overlay
  GIT_SSL_NO_VERIFY: "true"
  TEST_IMAGE: $registry/$organization/$CI_PROJECT_NAME
  RELEASE_IMAGE: $registry/$organization/$CI_PROJECT_NAME

  BUILD_TAG: ${CI_COMMIT_TAG}
  CONTAINER_NAME: ${CI_PROJECT_NAME}-${CI_JOB_ID}

before_script:
  - docker login -u $docker_user -p $docker_password $registry

syntax_check:
  stage: check
  script:
    - docker run -t --rm -v `pwd`:/root/ projectatomic/dockerfile-lint dockerfile_lint [-f Dockerfile]
    - >
    - docker run -t --rm -v `pwd`:/root/ projectatomic/dockerfile-lint dockerfile_lint [-f Dockerfile] |
      grep 'Error' &> /dev/null
      && (echo 'Idempotence test - fail' && exit 1)
      || (echo 'Idempotence test - pass' && exit 0)
  tags:
    - docker-ucp

build_docker_image:
  stage: build
  script:
    - docker pull $registry/$organization/$CI_PROJECT_NAME
    - docker build --build-arg JQ_VERSION=${BUILD_TAG} --build-arg GIT_COMMIT=${CI_COMMIT_SHA} --pull -t $TEST_IMAGE:$BUILD_TAG .
  tags:
    - docker
  only:
    - tags

#test_docker_image:
#  stage: test
#  image: $TEST_IMAGE:$BUILD_TAG
#  script:
#    - >
#      curl -k -X GET https://gitlab.lifecare.com/api/v4/version | jq .message
#      && (echo 'Idempotence test: pass' && exit 0)
#      || (echo 'Idempotence test: fail' && exit 1)
#    - >
#    - docker rm -f ${CONTAINER_NAME}
#  tags:
#    - docker
#  only:
#    - tags
#  when: on_success

deploy_docker_image:
  stage: deploy
  script:
    - docker push $TEST_IMAGE:$BUILD_TAG
  tags:
    - docker
  only:
    - tags
  when: on_success

release_docker_image:
  stage: release
  script:
    - docker run -d --name ${CONTAINER_NAME} $TEST_IMAGE:$BUILD_TAG
    - export VERSION=$(docker exec -i ${CONTAINER_NAME} cat /VERSION)
    - docker rm -f ${CONTAINER_NAME}
    - docker tag $TEST_IMAGE:$BUILD_TAG $RELEASE_IMAGE:${VERSION}
    - docker push $RELEASE_IMAGE:${VERSION}
    - docker tag $RELEASE_IMAGE:${VERSION} $RELEASE_IMAGE:latest
    - docker image rm -f $RELEASE_IMAGE:${VERSION}
    - docker push $RELEASE_IMAGE:latest
  tags:
    - docker
  only:
    - tags
  when: on_success
  
cleanup_docker_build:
  stage: cleanup
  script:
    - docker image rm -f $TEST_IMAGE:$BUILD_TAG
  tags:
    - docker
  only:
    - tags
  when: always 
  allow_failure: true
