---
language: ruby
sudo: required
services:
  - docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=kurrier/docker_alpine_jq
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64 

script:
 - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
 - export REPO=kurrier/alpine-jq
 - docker build -t $REPO:$TAG -f Dockerfile .

after_success:
 - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
 - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
   docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER;
   docker push $REPO:$TRAVIS_BUILD_NUMBER;
   fi 
 - docker push $REPO:$TAG
